es_ES missing translations done, punctuation marks, accent marks and exclamation marks fixed
Sudomemo/sudomemo-locales pull request #542
Opened 2023-07-21 01:07 UTC by funnym0th

2023-07-26 04:08 UTC, meemo requested changes
Looks good! Just a couple changes

2023-07-26 04:08 UTC, meemo commented on es_ES/LC_MESSAGES/archive.po
> +msgstr "Flipnote principal"
This should be changed to "Flipnote original" in order to be consistent with ORIGINAL_FLIPNOTE, or ORIGINAL_FLIPNOTE should be changed to match this. I'm not sure why there are multiple strings but it's what we have.

2023-07-26 04:08 UTC, meemo commented on es_ES/LC_MESSAGES/archive.po
> +msgstr "Flipnotes de %s de Flipnote Hatena, %s"
Maybe "Flipnotes por %s" instead of de? Por implies it being the user's creation while de implies ownership to me.

2023-07-26 04:08 UTC, meemo commented on es_ES/LC_MESSAGES/mail_new_friend.po
> +msgstr "¡Uno de tus amigos de Flipnote, %s, está en Sudomemo! ¿No es genial?"
I don't think I've heard "No es genial" used like that before, we might want to stick to something like "Que genial" instead.

2023-07-26 04:09 UTC, meemo commented on es_ES/LC_MESSAGES/archive.po
> +msgstr "Para más información, por favor lee el %sFAQ%."
The `s` in `%s` at the end here got cut off.

2024-02-02 20:05 UTC, closed without merging

2024-02-02 20:06 UTC, sudofox commented
closed (stale)
re-fork off latest and reapply changes if you wish to reopen